{{- if .Values.koordlet.enableServiceMonitor }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    koord-app: koordlet
  name: koordlet-service-monitor
  namespace: {{ .Values.installation.namespace }}
spec:
  endpoints:
  - interval: 30s
    port: http
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
    scheme: http
  jobLabel: koord-app
  selector:
    matchLabels:
      koord-app: koordlet

{{- end }}
