apiVersion: v1
kind: ServiceAccount
metadata:
  name: yarn-nodemanager
  namespace: {{ .Values.installation.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: yarn-nodemanager-role
  namespace: {{ .Values.installation.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
      - update
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yarn-nodemanager-rolebinding
  namespace : {{ .Values.installation.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yarn-nodemanager-role
subjects:
  - kind: ServiceAccount
    name: yarn-nodemanager
    namespace: {{ .Values.installation.namespace }}