apiVersion: v1
kind: ConfigMap
metadata:
  name: koord-scheduler-config
  namespace: {{ .Values.installation.namespace }}
data:
  koord-scheduler-config: |
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    kind: KubeSchedulerConfiguration
    profiles:
      - pluginConfig:
        - name: NodeResourcesFit
          args:
            apiVersion: kubescheduler.config.k8s.io/v1beta2
            kind: NodeResourcesFitArgs
            scoringStrategy:
              type: LeastAllocated
              resources:
                - name: cpu
                  weight: 1
                - name: memory
                  weight: 1
                - name: "koordinator.sh/batch-cpu"
                  weight: 1
                - name: "koordinator.sh/batch-mem"
                  weight: 1
        - name: LoadAwareScheduling
          args:
            apiVersion: kubescheduler.config.k8s.io/v1beta2
            kind: LoadAwareSchedulingArgs
            filterExpiredNodeMetrics: true
            nodeMetricExpirationSeconds: 300
            resourceWeights:
              cpu: 1
              memory: 1
            usageThresholds:
              cpu: 75
              memory: 85
            estimatedScalingFactors:
              cpu: 80
              memory: 70
        plugins:
          preFilter:
            enabled:
              - name: NodeNUMAResource
          filter:
            enabled:
              - name: LoadAwareScheduling
              - name: NodeNUMAResource
{{- if semverCompare "<= 1.20-0" .Capabilities.KubeVersion.Version }} 
          postFilter:
            disabled:
              - name: DefaultPreemption
            enabled:
              - name: CompatibleDefaultPreemption
{{- end }}
          score:
            enabled:
              - name: LoadAwareScheduling
                weight: 1
              - name: NodeNUMAResource
                weight: 1
          reserve:
            enabled:
              - name: LoadAwareScheduling
              - name: NodeNUMAResource
          preBind:
            enabled:
              - name: NodeNUMAResource
        schedulerName: koord-scheduler