apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: koordinator-mutating-webhook-configuration
  annotations:
    template: ""
webhooks:
{{ if contains "PodMutatingWebhook=false" .Values.featureGates }}{{ else }}
- clientConfig:
    caBundle: Cg==
    service:
      name: koordinator-webhook-service
      namespace: {{ .Values.installation.namespace }}
      path: /mutate-pod
  failurePolicy: {{ .Values.webhookConfiguration.failurePolicy.pods }}
  admissionReviewVersions:
  - v1
  - v1beta1
  sideEffects: None
  timeoutSeconds: {{ .Values.webhookConfiguration.timeoutSeconds }}
  name: mpod.kb.io
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: DoesNotExist
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
{{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: koordinator-validating-webhook-configuration
  annotations:
    template: ""
webhooks:
{{- if contains "PodValidatingWebhook=false" .Values.featureGates }}{{ else }}
- clientConfig:
    caBundle: Cg==
    service:
      name: koordinator-webhook-service
      namespace: {{ .Values.installation.namespace }}
      path: /validate-pod
  failurePolicy: {{ .Values.webhookConfiguration.failurePolicy.pods }}
  admissionReviewVersions:
  - v1
  - v1beta1
  sideEffects: None
  timeoutSeconds: {{ .Values.webhookConfiguration.timeoutSeconds }}
  name: vpod.kb.io
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: DoesNotExist
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
{{- end }}
