apiVersion: v1
kind: Service
metadata:
  name: koord-yarn-operator-service
  namespace: {{ .Values.installation.namespace }}
spec:
  selector:
    koord-app: koord-yarn-operator
  type: ClusterIP
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: koord-yarn-operator
  namespace: {{ .Values.installation.namespace }}
  labels:
    koord-app: koord-yarn-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      koord-app: koord-yarn-operator
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        koord-app: koord-yarn-operator
    spec:
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml . | nindent 8 }}
{{- end }}
      containers:
        - args:
            - --enable-leader-election
            - --metrics-addr={{ .Values.koordYarnOperator.metrics.addr }}:{{ .Values.koordYarnOperator.metrics.port }}
            - --logtostderr=true
            - --leader-election-namespace={{ .Values.installation.namespace }}
            - --v={{ .Values.koordYarnOperator.log.level }}
            - --sync-period={{ .Values.koordYarnOperator.resyncPeriod }}
          command:
            - /koord-yarn-operator
          image: {{ .Values.imageRepositoryHost }}/{{ .Values.koordYarnOperator.image.repository }}:{{ .Values.koordYarnOperator.image.tag }}
          imagePullPolicy: Always
          name: yarn-operator
          env:
          - name: HADOOP_CONF_DIR
            value: /etc/hadoop-conf
          ports:
            - containerPort: {{ .Values.koordYarnOperator.metrics.port }}
              name: metrics
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.koordYarnOperator.metrics.port }}
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.koordYarnOperator.metrics.port }}
            failureThreshold: 30
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.koordYarnOperator.metrics.port }}
            failureThreshold: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.koordYarnOperator.resources | nindent 12 }}
          volumeMounts:
            - name: yarn-config-volume
              mountPath: /etc/hadoop-conf
      volumes:
        - name: yarn-config-volume
          configMap:
            name: yarn-config
      hostNetwork: {{ .Values.koordYarnOperator.hostNetwork }}
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      serviceAccountName: koord-yarn-operator
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: koord-app
                      operator: In
                      values:
                        - koord-yarn-operator
                topologyKey: kubernetes.io/hostname
              weight: 100
{{- with .Values.koordYarnOperator.nodeAffinity }}
        nodeAffinity:
{{ toYaml . | indent 10 }}
{{- end }}

{{- if .Values.koordYarnOperator.nodeSelector }}
        nodeSelector:
{{ toYaml .Values.koordYarnOperator.nodeSelector | indent 8 }}
{{- end }}

{{- if .Values.koordYarnOperator.tolerations }}
        tolerations:
{{ toYaml .Values.koordYarnOperator.tolerations | indent 8 }}
{{- end }}
