apiVersion: scheduling.k8s.io/v1
description: Run lowest-priority offline batch jobs, generally refers to not making resource budgets.
kind: PriorityClass
metadata:
  name: koord-free
preemptionPolicy: PreemptLowerPriority
value: 3000