apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.installation.namespace }}
  name: {{ .Values.yarn.resourceManager.serviceName }}
  labels:
    app.kubernetes.io/name: {{ include "hadoop-yarn.name" . }}
    helm.sh/chart: {{ include "hadoop-yarn.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: yarn-rm-service
spec:
  ports:
  - port: {{ .Values.yarn.resourceManager.webPort }}
    name: web
  - port: 8033
    name: admin-addr
  - port: 8031
    name: res-tracker-addr
  - port: 8032
    name: addr
  - port: 8030
    name: scheduler-addr
{{- if .Values.hdfs.enabled }}
  - port: 9000
    name: hdfs-namenode
  - port: {{ .Values.hdfs.nameNode.httpPort }}
    name: hdfs-http
{{- end }}
  type: {{ .Values.yarn.resourceManager.serviceType }}
  selector:
    app.kubernetes.io/name: {{ include "hadoop-yarn.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: yarn-rm