{{- if .Values.koordlet.enableServiceMonitor }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    koord-app: koordlet
  name: koordlet-service
  namespace: {{ .Values.installation.namespace }}
spec:
  clusterIP: None
  ports:
  # TODO: Support port in values
  - name: http
    port: 9316
    targetPort: 9316
  selector:
    koord-app: koordlet

{{- end }}
