apiVersion: v1
kind: ConfigMap
metadata:
  name: yarn-config
  namespace: {{ .Values.installation.namespace }}
data:
  yarn-site.xml: |
    <configuration>
        <property>
            <name>yarn.resourcemanager.admin.address</name>
            <value>{{ .Values.yarnConfiguration.resourceManager.address }}:{{ .Values.yarnConfiguration.resourceManager.adminPort }}</value>
        </property>
        <property>
            <name>yarn.resourcemanager.address</name>
            <value>{{ .Values.yarnConfiguration.resourceManager.address }}:{{ .Values.yarnConfiguration.resourceManager.port }}</value>
        </property>
    </configuration>
  core-site.xml: |
    <configuration>
    </configuration>