apiVersion: v1
kind: ServiceAccount
metadata:
  name: koord-yarn-operator
  namespace: {{ .Values.installation.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: koord-yarn-operator-role:leaderelection
  namespace: {{ .Values.installation.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - configmaps/status
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
      - update
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: koord-yarn-operator-rolebinding:leaderelection
  namespace: {{ .Values.installation.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: koord-yarn-operator-role:leaderelection
subjects:
  - kind: ServiceAccount
    name: koord-yarn-operator
    namespace: {{ .Values.installation.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: koord-yarn-operator-cluserrole
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - configmaps/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/status
      - pods
      - pods/status
      - namespaces
      - events
    verbs:
      - patch
      - update
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: koord-yarn-operator-custom-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: koord-yarn-operator-cluserrole
subjects:
  - kind: ServiceAccount
    name: koord-yarn-operator
    namespace: {{ .Values.installation.namespace }}